#include "eif_eiffel.h"
#include "eif_rout_obj.h"

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1058_8333(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F1039_8338(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F1039_8339(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F1058_8332(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F1039_8337(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F1002_8333(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F1002_8332(EIF_REFERENCE, EIF_TYPED_VALUE);
extern void F139_7136(EIF_REFERENCE, EIF_TYPED_VALUE);

#ifdef __cplusplus
}
#endif
